### PR TITLE
Fix issues assigned to Milestone M5

### LINKED ISSUE #22: Lost fail message when fail threshold is met
when the verify function throws a message.str() exception, the main method cannot correctly accept this exception and skips to the default exception handling. 

image

### LINKED ISSUE #24: Incorrect return type for function get_tests_failed_total
The result of function [`get_tests_failed_total` is returned as value of `main`](https://github.com/sigcpp/stl-lite/blob/4e56c9059101d4a35ce2741f304ac171999c3b6f/test/driver.cpp#L90) whose return type is `int`, but `get_tests_failed_total` returns `unsigned`.

In general, the [various counters in `tester.cpp`](https://github.com/sigcpp/stl-lite/blob/4e56c9059101d4a35ce2741f304ac171999c3b6f/test/tester.cpp#L68-L71) and the fail threshold should be `int` in order to ensure that the return value from `main` is not mistaken for an error code. (`main` returns a negative value if there is any error.)

### PR DESCRIPTION
**Pull request by smurthys**
The changes in this PR fix issues assigned to M5. This PR should be closed as the last act of closing M5. This PR summary to be updated with additional issues fixed as the day proceeds and more issues are fixed.

Fixes #22, #24 

Summary of changes:
- Custom error classes for verifier errors (including fail threshold met)
- Handle verifier errors and completely revamp error handling in test driver
- Change data type of counters and fail threshold to `int` in tester

### CODE REVIEW

**Comment by smurthys** [comment]
@cmcmone Would you please merge this branch to string_view-test and verify that issue #22  is indeed fixed? I have verified it, but I'd like you to verify as well. Thank you

**Comment by cmcmone** [comment]
I verified and it works well! thank you @smurthys

**Comment by smurthys** [comment]
I'd love to get a review of this branch. Thank you

**Comment by smurthys** [comment]
I pushed a change that fixes the incorrect enum value we spotted in the call today. Unless we find issues, I don't expect any more additions to this branch.

File: test/driver.cpp [hunk 1]
```diff
@@ -53,41 +70,68 @@ int main(int argc, char* argv[])
...
+		if (options.fom != file_open_mode::no_file)
+			std::cout << message << '\n'; //not calling show_error because message is already formatted 
 	}
 
+	//print summary because one or more tests may have been run
 	if (options.summary)
 		summarize_tests();
 
-	return get_tests_failed_total();
+	//return totaly tests failed only if there was no error: the caller should know if there was an error
```
Comment (Ndemco) [inline test/driver.cpp:130]: Typo in comment.

```suggestion
	//return total tests failed only if there was no error: the caller should know if there was an error
```

**Review by Ndemco — APPROVED** [review]
Just reviewed and tested, I believe this is ready to merge. Thank you @smurthys and @cmcmone for your contributions to this PR.

**Review by cmcmone — APPROVED** [review]
Everything looks good. Thanks @smurthys @Ndemco

**Comment by smurthys** [comment]
There is a small likelihood of merge conflicts with this PR once PR #23 is merged, and we will know as soon as #23 is merged. If there are merge conflicts, I recommend doing the merge on a call tomorrow. It is highly likely that PR #27 will also be ready for merging by then.

**Comment by smurthys** [comment]
Thanks @cmcmone and @Ndemco for the reviews
